version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:8.11.2
    steps:
      - run:
          name: Run Tests
          command: npm run build

workflows:
  test_my_app:
    jobs:
      - test
